global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: lyw-backend
    metrics_path: /lyw/actuator/prometheus
    static_configs:
      - targets:
          - lyw-backend:8080
