package com.jiawa.lyw.itineraryplanning.domain;

public enum PlanningError {
    INVALID_REQUEST,
    INVALID_OPERATION,
    INVALID_DATE,
    DATE_OUT_OF_RANGE,
    INVALID_TIME,
    TIME_CONFLICT,
    INVALID_PLACE,
    INVALID_COST,
    BUDGET_EXCEEDED,
    ITEM_NOT_FOUND,
    INVALID_REORDER,
    UNSUPPORTED_CONTRACT,
    DUPLICATE_OPERATION,
    INVALID_KNOWLEDGE_REFERENCE,
    TOO_MANY_OPERATIONS
}
